emp:
  info:
    address: Hydrabad
    company-details:
      title: Realcoderz
    friends:
    - Sri-nath
    - raja
    - Sri-nath
    id: 100
    id-details:
      title: HCK
    mobile-number:
    - 999999999999
    - 888888888888
    - 777777777777
    - 666666666666
    name: Arvind Verma
    team-member:
    - Ansu
    - pooja
    - priya
    - Akash
